FROM node:18-alpine
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
WORKDIR C:\Users\Vitaliy\AppData\Roaming\pypoetry\venv\docker-app
COPY . .
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]